export enum Labels {
  companyName = "Aroma shop",
  search = "Поиск",
  sets = "Наборы",
  catalog = "Каталог",
  aroms = "Ароматы",
  production = "Производство",
  contacts = "Контакты",
  candleSale = "Свечи по скидке",
  freshAir = "Свежее дыхание в вашей жизни",
  mostPopular = "Самое популярное",
  highQuality = "Высокое качество ONLY",
  supportManager = "Поддержка менеджера 24/7",
  completeOrder = "Выполнение заказа в TURBO-режиме",
  mostPopularDesc = "Товары, которые наиболее часто заказывают наши клиенты",
  previewDesc = "Мы отвечаем за качество и стараемся над нашей продукции для того, чтобы вы смогли сконцентрироваться над важными задачами и расслабиться после тяжелого рабочего дня.",
}
